[package]
name = "es-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-cpuid = "10.6.0"

[features]
nightly = []

[build]
rustflags = ["-C", "target-feature=+sse,+sse2"]
